#!/usr/bin/env node
//
// liturgical-golden.mjs
//
// Guards the three liturgical-engine copies against drift
// (swift-app/kalendar/Models/LiturgicalCalendar.swift, swift-app/KalendarWidget/LiturgicalCalendar.swift,
// and expo-app/src/engine/kalendar-engine.js). It computes liturgicalInfo() for every day of a
// decade using the JS engine and writes two artifacts that share one source of truth:
//
//   * tools/liturgical-golden.txt          - canonical golden, verified here.
//   * swift-app/KalendarTests/LiturgicalGolden.swift - the same lines embedded for
//                                            the Swift test (KalendarTests) to check the two
//                                            Swift copies against.
//
// Usage:
//   node tools/liturgical-golden.mjs --write    Regenerate both artifacts.
//   node tools/liturgical-golden.mjs            Verify the JS engine still matches
//                                               the committed golden (exit 1 if not).
//
// The Swift test does the mirror check for the Swift engine. So editing any one copy
// without updating the others fails a check before shipping.

import { readFileSync, writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';

const repoRoot = join(dirname(fileURLToPath(import.meta.url)), '..');
const enginePath = join(repoRoot, 'expo-app', 'src', 'engine', 'kalendar-engine.js');
const goldenTxtPath = join(repoRoot, 'tools', 'liturgical-golden.txt');
const swiftRoot = join(repoRoot, 'swift-app');
const goldenSwiftPath = join(swiftRoot, 'KalendarTests', 'LiturgicalGolden.swift');
const appEnginePath = join(swiftRoot, 'kalendar', 'Models', 'LiturgicalCalendar.swift');
const widgetEnginePath = join(swiftRoot, 'KalendarWidget', 'LiturgicalCalendar.swift');

// The widget copy is not compiled into the Swift test target, so guard it with a
// direct source comparison: everything from `import SwiftUI` onward must match the
// app copy exactly (only the file's header comment may differ).
function bodyAfterImport(path) {
  const src = readFileSync(path, 'utf8');
  const idx = src.indexOf('\nimport SwiftUI');
  return idx === -1 ? src : src.slice(idx);
}

function checkWidgetCopyInSync() {
  if (bodyAfterImport(appEnginePath) !== bodyAfterImport(widgetEnginePath)) {
    console.error('swift-app/KalendarWidget/LiturgicalCalendar.swift has drifted from the app copy.');
    console.error('The two Swift engine copies must stay identical below their headers.');
    process.exit(1);
  }
}

// The decade covered by the golden. Kept as a stable, hand-auditable range.
const START_YEAR = 2025;
const END_YEAR = 2034;

// Load the engine (an ES module with no imports) from its source. Importing it
// as a data: URL sidesteps the Expo app's CommonJS package.json, which would
// otherwise make Node treat the .js file as CommonJS.
async function loadEngine() {
  const src = readFileSync(enginePath, 'utf8');
  return import('data:text/javascript;base64,' + Buffer.from(src).toString('base64'));
}

const ENGINE = await loadEngine();

// One compact line per day:
// YYYY-MM-DD|season|color|solemnity|week|feastName|title|civilHoliday
function lineFor(engine, date) {
  const info = engine.liturgicalInfo(date);
  const y = date.getFullYear();
  const m = String(date.getMonth() + 1).padStart(2, '0');
  const d = String(date.getDate()).padStart(2, '0');
  const week = info.weekOfSeason == null ? '' : String(info.weekOfSeason);
  const feast = info.feastName == null ? '' : info.feastName;
  const title = engine.liturgicalDayTitle(info, date) || '';
  const civil = info.civilHolidayName == null ? '' : info.civilHolidayName;
  return `${y}-${m}-${d}|${info.season}|${info.color.name}|${info.isSolemnity ? 1 : 0}|${week}|${feast}|${title}|${civil}`;
}

function computeGolden() {
  const engine = ENGINE;
  const lines = [];
  for (let year = START_YEAR; year <= END_YEAR; year++) {
    for (let month = 0; month < 12; month++) {
      let day = 1;
      while (true) {
        const date = new Date(year, month, day);
        if (date.getMonth() !== month) break; // rolled into next month
        lines.push(lineFor(engine, date));
        day++;
      }
    }
  }
  return lines.join('\n') + '\n';
}

const BANNER =
  '// Generated by tools/liturgical-golden.mjs --write. Do not edit by hand.\n' +
  '// Expected liturgicalInfo output for every day of ' + START_YEAR + '-' + END_YEAR + ',\n' +
  '// one line per day: YYYY-MM-DD|season|color|solemnity|week|feastName|title|civilHoliday\n';

function swiftFileFor(golden) {
  return (
    BANNER +
    '\n' +
    'enum LiturgicalGolden {\n' +
    '    static let lines = """\n' +
    golden.trimEnd() + '\n' +
    '"""\n' +
    '}\n'
  );
}

function write() {
  const golden = computeGolden();
  writeFileSync(goldenTxtPath, golden);
  writeFileSync(goldenSwiftPath, swiftFileFor(golden));
  const count = golden.trimEnd().split('\n').length;
  console.log(`Wrote ${count} days to tools/liturgical-golden.txt and swift-app/KalendarTests/LiturgicalGolden.swift`);
}

function verify() {
  const computed = computeGolden();
  let committed;
  try {
    committed = readFileSync(goldenTxtPath, 'utf8');
  } catch {
    console.error('No golden file. Run: node tools/liturgical-golden.mjs --write');
    process.exit(1);
  }
  if (computed !== committed) {
    const a = computed.trimEnd().split('\n');
    const b = committed.trimEnd().split('\n');
    const max = Math.max(a.length, b.length);
    for (let i = 0; i < max; i++) {
      if (a[i] !== b[i]) {
        console.error('JS engine drifted from the golden at line ' + (i + 1) + ':');
        console.error('  committed: ' + (b[i] ?? '(missing)'));
        console.error('  computed:  ' + (a[i] ?? '(missing)'));
        break;
      }
    }
    process.exit(1);
  }
  // The Swift golden must embed exactly the same lines.
  const swift = readFileSync(goldenSwiftPath, 'utf8');
  if (!swift.includes(computed.trimEnd())) {
    console.error('swift-app/KalendarTests/LiturgicalGolden.swift is out of sync with the golden.');
    console.error('Run: node tools/liturgical-golden.mjs --write');
    process.exit(1);
  }
  checkWidgetCopyInSync();
  console.log('JS engine matches the golden (' + computed.trimEnd().split('\n').length + ' days).');
  console.log('Widget engine copy is in sync with the app copy.');
}

if (process.argv.includes('--write')) {
  write();
} else {
  verify();
}
